// flow-typed signature: 3ae0f0524c4df26982a0cc9e6cd9e77d
// flow-typed version: <<STUB>>/i18next-browser-languagedetector_v^5.0.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-browser-languagedetector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-browser-languagedetector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-browser-languagedetector/dist/cjs/i18nextBrowserLanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/esm/i18nextBrowserLanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-browser-languagedetector/dist/cjs/i18nextBrowserLanguageDetector.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/cjs/i18nextBrowserLanguageDetector'>;
}
declare module 'i18next-browser-languagedetector/dist/esm/i18nextBrowserLanguageDetector.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/esm/i18nextBrowserLanguageDetector'>;
}
declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector'>;
}
declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min'>;
}
declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/i18nextBrowserLanguageDetector'>;
}
declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.min.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.min'>;
}
declare module 'i18next-browser-languagedetector/index' {
  declare module.exports: $Exports<'i18next-browser-languagedetector'>;
}
declare module 'i18next-browser-languagedetector/index.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector'>;
}
