// flow-typed signature: 4742c04ddb9e700a2d1beab0f4e7e091
// flow-typed version: <<STUB>>/react-responsive_v^8.1.0/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive/dist/react-responsive' {
  declare module.exports: any;
}

declare module 'react-responsive/dist/react-responsive.min' {
  declare module.exports: any;
}

declare module 'react-responsive/src/Component' {
  declare module.exports: any;
}

declare module 'react-responsive/src/Context' {
  declare module.exports: any;
}

declare module 'react-responsive/src' {
  declare module.exports: any;
}

declare module 'react-responsive/src/mediaQuery' {
  declare module.exports: any;
}

declare module 'react-responsive/src/toQuery' {
  declare module.exports: any;
}

declare module 'react-responsive/src/useMediaQuery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive/dist/react-responsive.js' {
  declare module.exports: $Exports<'react-responsive/dist/react-responsive'>;
}
declare module 'react-responsive/dist/react-responsive.min.js' {
  declare module.exports: $Exports<'react-responsive/dist/react-responsive.min'>;
}
declare module 'react-responsive/src/Component.js' {
  declare module.exports: $Exports<'react-responsive/src/Component'>;
}
declare module 'react-responsive/src/Context.js' {
  declare module.exports: $Exports<'react-responsive/src/Context'>;
}
declare module 'react-responsive/src/index' {
  declare module.exports: $Exports<'react-responsive/src'>;
}
declare module 'react-responsive/src/index.js' {
  declare module.exports: $Exports<'react-responsive/src'>;
}
declare module 'react-responsive/src/mediaQuery.js' {
  declare module.exports: $Exports<'react-responsive/src/mediaQuery'>;
}
declare module 'react-responsive/src/toQuery.js' {
  declare module.exports: $Exports<'react-responsive/src/toQuery'>;
}
declare module 'react-responsive/src/useMediaQuery.js' {
  declare module.exports: $Exports<'react-responsive/src/useMediaQuery'>;
}
