// flow-typed signature: fb81e1de7075a66187244bb041b8c1f8
// flow-typed version: <<STUB>>/sanitize.css_v^12.0.1/flow_v0.136.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
